/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'walle' at '4/28/16 1:39 PM' with Gradle 2.3
 *
 * @author walle, @date 4/28/16 1:39 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
